name: goreleaser

on:
  workflow_run:
    workflows: ["gotests"]
    types:
      - completed
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  goreleaser:
    if: ${{ github.event_name == 'push' && github.ref_type == 'tag' && github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      -
        name: Set up Go
        uses: actions/setup-go@v4
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          #args: release --clean --skip=publish
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}